config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :edi_ftp_servers
    resources :edi_tasks
    resources :edi_logs
  end

end

app/models/edi_ftp_server.rb
# == Schema Information
#
# Table name: edi_ftp_servers
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  hostname    :string(255)      not null
#  port        :integer          not null
#  username    :string(255)      not null
#  password    :string(255)      not null
#  protocol    :string(255)      not null
#  last_status :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class EdiFtpServer < ActiveRecord::Base
  self.table_name = "edi_ftp_servers"
  has_many :edi_tasks
  validates_presence_of :name, :hostname, :port, :username, :password, :protocol
  validates :protocol, inclusion: {in: %w(ftp sftp ftps),
                                   message: "%{value} is not a valid protocol"}

  def to_s
    "#{protocol}://#{username}@#{hostname}:#{port}"
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end
end

app/models/edi_log.rb
class EdiLog < ActiveRecord::Base
  belongs_to :edi_task
  validates_presence_of :timestamp, :edi_task_id, :result

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end
end

app/models/edi_task.rb
# == Schema Information
#
# Table name: edi_schedules
#
#  id                    :integer          not null, primary key
#  task_type             :string(255)      default(""), not null
#  affiliate_id          :integer          not null
#  edi_ftp_server_id     :integer          not null
#  source_directory      :string(255)      not null
#  source_filemask       :string(255)      not null
#  destination_directory :string(255)      not null
#  notify_email          :string(255)
#  edi_printer_id        :integer
#  last_executed         :datetime
#  last_status           :text(65535)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class EdiTask < ActiveRecord::Base
  self.table_name = "edi_tasks"
  belongs_to :affiliate
  belongs_to :edi_ftp_server
  belongs_to :printer
  validates :task_type, inclusion: {in: %w(download upload),
                                    message: "%{value} is not a valid task"}

  def to_s
    "#{task_type} #{affiliate} #{document_type}"
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end
end

app/controllers/admin/edi_ftp_servers_controller.rb
class Admin::EdiFtpServersController < Admin::BaseController
  def index
    authorize EdiFtpServer.new
    @edi_ftp_servers = EdiFtpServer.paginate(page: params[:page], per_page: @per_page).order('name')
  end

  def new
    @edi_ftp_server = authorize EdiFtpServer.new(name: 'New edi_ftp_server', protocol: :sftp)
    render 'edit'
  end

  def create
    @edi_ftp_server = authorize EdiFtpServer.new(edi_ftp_server_params)

    if @edi_ftp_server.save
      Rails.cache.delete :edi_ftp_servers
      redirect_to action: 'index', notice: 'FTP server was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @edi_ftp_server = authorize EdiFtpServer.find(params[:id])
  end

  def edit
    @edi_ftp_server = authorize EdiFtpServer.find(params[:id])
  end

  def update
    @edi_ftp_server = authorize EdiFtpServer.find(params[:id])

    if @edi_ftp_server.update(edi_ftp_server_params)
      redirect_to action: 'index', notice: 'FTP server was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @edi_ftp_server = authorize EdiFtpServer.find(params[:id])
    @edi_ftp_server.destroy

    redirect_to action: 'index', notice: 'FTP server has been deleted.'
  end


  private

  def edi_ftp_server_params
    params.require(:edi_ftp_server).permit!
  end
end

app/controllers/admin/edi_tasks_controller.rb
class Admin::EdiTasksController < Admin::BaseController
  def index
    authorize EdiTask.new
    @edi_tasks = EdiTask.paginate(page: params[:page], per_page: @per_page).order(:affiliate_id)
  end

  def new
    @edi_task = authorize EdiTask.new(task_type: :download)
    render 'edit'
  end

  def create
    @edi_task = authorize EdiTask.new(edi_task_params)

    if @edi_task.save
      Rails.cache.delete :edi_tasks
      redirect_to action: 'index', notice: 'Task was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @edi_task = authorize EdiTask.find(params[:id])
  end

  def edit
    @edi_task = authorize EdiTask.find(params[:id])
  end

  def update
    @edi_task = authorize EdiTask.find(params[:id])

    if @edi_task.update(edi_task_params)
      redirect_to action: 'index', notice: 'Task was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @edi_task = authorize EdiTask.find(params[:id])
    @edi_task.destroy

    redirect_to action: 'index', notice: 'Task has been deleted.'
  end


  private

  def edi_task_params
    params.require(:edi_task).permit!
  end
end

app/views/admin/edi_ftp_servers/edit.html.erb
git <h2><i class="fa fa-server"></i> <%= @edi_ftp_server.name %></h2>
<hr/>

<%= simple_form_for [:admin, @edi_ftp_server] do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>
  <%= f.input :name %>
  <%= f.input :hostname %>
  <%= f.input :port %>
  <%= f.input :protocol, collection: [['SFTP', :sftp], ['FTP', :ftp], ['FTPS', :ftps]] %>
  <%= f.input :username %>
  <%= f.input :password, as: :string %>

  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>




<% content_for :title do %>
  <%= @edi_ftp_server.name %>
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">EDI Settings</a></li>
  <li><%= link_to "Printers", admin_edi_ftp_servers_path %></li>
  <li class="active"><%= @edi_ftp_server.name %></li>
<% end %>

app/views/admin/edi_ftp_servers/index.html.erb
<%= link_to new_admin_edi_ftp_server_path, class: 'pull-right btn btn-sm btn-default' do %>
  <i class="fa fa-plus"></i> New FTP server
<% end %>
<h2><i class="fa fa-server"></i> FTP Servers</h2>
<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Last Accessed</th>
    <th>Result</th>
    <th class="actions">&nbsp;</th>
  </tr>
  <% @edi_ftp_servers.each do |ftp| %>
    <tr>
      <td><%= ftp.name %></td>
      <td><code><%= ftp.protocol %>://<%= ftp.username %>@<%= ftp.hostname %>:<%= ftp.port %></code></td>
      <td>
        <% if ftp.last_status.blank? %>
          <span class="light">- never -</span>
        <% else %>
          <%= systime ftp.updated_at %>
        <% end %>
      </td>
      <td class="<%= 'text-danger' if ftp.last_status != 'ok' %>"><%= truncate ftp.last_status, length: 40 %></td>
      <td class="actions">
        <%= link_to "edit", edit_admin_edi_ftp_server_path(ftp) %> &nbsp;
        <%= link_to "delete",
                    {action: "destroy", id: ftp.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @edi_ftp_servers %>


<% content_for :title do %>
  EDI FTP Servers
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">EDI Settings</a></li>
  <li class="active">FTP Server</li>
<% end %>

app/views/admin/edi_logs/index.html.erb
<h2>Log</h2>

<table class="table table-striped table-condensed">
  <tr>
    <th><%= sortable "edi_logs.id", "ID" %></th>
    <th><%= sortable "timestamp" %></th>
    <th><%= sortable "core_affiliates.name", "Affiliate" %></th>
    <th><%= sortable "edi_tasks.document_type", "Document" %></th>
    <th><%= sortable "edi_tasks.task_type", "Task" %>
    <th><%= sortable "result" %></th>
    <th>Files</th>
    <th>Error</th>
    <th class="actions">&nbsp;</th>
  </tr>
  <% @edi_logs.each do |log| %>
    <tr>
      <td><%= log.id %></td>
      <td><%= systime log.timestamp %></td>
      <td><%= log.edi_task.affiliate %></td>
      <td><%= log.edi_task.document_type %></td>
      <td><%= log.edi_task.task_type %></td>
      <td><%= log.result %></td>
      <td><%= log.file_path %></td>
      <td><%= truncate log.error_message, length: 30 %></td>
      <td class="actions">
        <%= link_to "view", admin_edi_log_path(log) %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @edi_logs %>


<% content_for :title do %>
  EDI Printers
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">EDI Settings</a></li>
  <li class="active">Printers</li>
<% end %>

app/views/admin/edi_logs/show.html.erb
<h1>Admin::EdiLogs#show</h1>
<p>Find me in app/views/admin/edi_logs/show.html.erb</p>

app/views/admin/edi_tasks/_edi_task.html.erb
<tr>
  <td><i class="fa fa-<%= edi_task.task_type %>"></i></td>
  <td><%= edi_task.edi_ftp_server.name %></td>
  <td><%= edi_task.affiliate.name %></td>
  <td><%= edi_task.document_type.titlecase %></td>
  <td><%= edi_task.notify_email.presence || "-" %></td>
  <td><%= edi_task.printer.presence || "-" %></td>
  <td><%= tick edi_task.active %></td>
  <td><%= edi_task.last_executed.nil? ? '- never ' : systime(edi_task.last_executed) %></td>
  <td class="<%= 'text-danger' if edi_task.last_status != 'ok' %>"><%= truncate edi_task.last_status, length: 40 %></td>
  <td class="actions">
    <%= link_to "edit", edit_admin_edi_task_path(edi_task) %> &nbsp;
    <%= link_to "delete",
                {action: "destroy", id: edi_task.id},
                method: :delete,
                data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/edi_tasks/edit.html.erb
<h2><i class="fa fa-clock-o"></i> <%= @edi_task.id %></h2>
<hr/>

<%= simple_form_for [:admin, @edi_task] do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>
  <%= f.input :task_type, collection: [['Download', :download], ['Upload', :upload]] %>
  <%= f.association :edi_ftp_server %>
  <%= f.association :affiliate %>
  <%= f.input :document_type, collection: [:orders, :packing_slips, :confirms, :inventory].map { |x| [x.to_s.titlecase, x] } %>
  <%= f.input :source_directory %>
  <%= f.input :source_filemask %>
  <%= f.input :destination_directory %>
  <%= f.input :notify_email %>
  <%= f.association :printer %>
  <%= f.input :active %>
  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>




<% content_for :title do %>
  EDI Schedule: <%= @edi_task.id %>
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">EDI Settings</a></li>
  <li><%= link_to "Tasks", admin_edi_tasks_path %></li>
  <li class="active"><%= @edi_task.id %></li>
<% end %>

app/views/admin/edi_tasks/index.html.erb
<%= link_to new_admin_edi_task_path, class: 'pull-right btn btn-sm btn-default' do %>
  <i class="fa fa-plus"></i> New EDI task
<% end %>
<h2><i class="fas fa-tasks"></i> EDI Tasks</h2>

<table class="table table-striped table-condensed">
  <tr>
    <th></th>
    <th>FTP Server</th>
    <th>Affiliate</th>
    <th>Document Type</th>
    <th>Email</th>
    <th>Printer</th>
    <th>Active</th>
    <th>Last run</th>
    <th>Result</th>
    <th class="actions">&nbsp;</th>
  </tr>
  <%= render @edi_tasks %>
</table>

<%= render 'admin/shared/table_summary', data: @edi_tasks %>


<% content_for :title do %>
  EDI Schedule
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">EDI Settings</a></li>
  <li class="active">Tasks</li>
<% end %>

app/views/admin/shared/_edi_menu.html.erb
<li class="<%= 'active' if request.original_url.include? 'admin/edi' %>">
  <a href="#"><i class="fa fa-exchange-alt fa-fw"></i> EDI Settings <span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <% if current_user.has_permission?('EdiFtpServer', 'index') %>
      <li><%= link_to "FTP Servers", admin_edi_ftp_servers_path %></li>
    <% end %>
    <% if current_user.has_permission?('EdiTask', 'index') %>
      <li><%= link_to "Tasks", admin_edi_tasks_path %></li>
    <% end %>
    <li><%= link_to "Log", admin_edi_logs_path %></li>
  </ul>
</li>

app/views/edi_logs/index.html.erb
<h1>EdiLogs#index</h1>
<p>Find me in app/views/edi_logs/index.html.erb</p>

app/views/edi_logs/show.html.erb
<h1>EdiLogs#show</h1>
<p>Find me in app/views/edi_logs/show.html.erb</p>

app/views/layouts/rhombus_edi/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RhombusEdi</title>
  <%= stylesheet_link_tag "rhombus_edi/application", media: "all" %>
  <%= javascript_include_tag "rhombus_edi/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>